### ISSUE TITLE
Metadata updates

### ISSUE THREAD

**Issue by peterregier** [COMPASS-DOE/EXCHANGE#19]
K001, K004, and K041 is missing from "EC1_Metadata_KitLevel.csv", "EC1_Data_CollectionLevel.csv", and "EC1_Metadata_CollectionLevel.csv". Also, "EC1_Metadata_KitLevel.csv" kit_ids are formatted as "004" instead of "K004".

**Comment by amyerspigg** [comment]
K041, K001 and K007 still missing: https://drive.google.com/file/d/1eXPh-873xVYcREOAsbZu3pEgU4k9ykf-/view

**Comment by amyerspigg** [comment]
@stephpenn1 do you have an update if K041 has been updated in the metadata sheet yet or not?

**Comment by stephpenn1** [comment]
@amyerspigg I thought you were going to fill out the form and I put it into the dataset? I don't see it in the form responses if so, but could be remembering wrong

**Comment by stephpenn1** [comment]
Done!
