### ISSUE TITLE
ESS-DIVE Data Package Structure To Do

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#31]
### Note: Deadline for ESS-DIVE submission October 15

End Product: ESS-DIVE data package with corrected Level 2 datasets, multiple zip files (one zip per sample type - soil, sediment, water). Multiple files (e.g. pH, TCTN) or folders (e.g. CDOM, FTICR) within each zip

What the data package would like like, separate zip files per `Analyte`:

![Screen Shot 2022-09-26 at 2 47 07 PM](https://user-images.githubusercontent.com/20341158/192356134-d5660523-ebda-4b6c-b31a-07f4d6b6f551.png)

#### Metadata
- [x] #19 Update missing Kit metadata for `K041`, `K001`, and `K007`
- [x] #30 in accordance with [sample id rep format](https://github.com/ess-dive-community/essdive-sample-id-metadata)

#### The Rest
- [x] #23
- [x] #27 @amyerspigg
- [x] check out [flmd format](https://github.com/ess-dive-community/essdive-file-level-metadata), is this something we want to use?
- [x] generally follow this [csv re format](https://github.com/ess-dive-community/essdive-csv-structure)
- [ ] #29 
- [x] As data files are completed (to level 2 stage), do thorough check for below criteria

**Comment by stephpenn1** [comment]
Each data file should meet the following criteria:
- [ ] File name: `[Campaign]_[Sample Type]_[Analyte]_Level2.csv`
- [ ] Missing values are `NA`
- [ ] Flag columns state reason for each `NA` value
- [ ] File is in flat CSV format
- [ ] No duplicate Kit_IDs

**Comment by stephpenn1** [comment]
What the data package would like like, seprate zip files per `Analyte`
![Screen Shot 2022-09-26 at 2 47 07 PM](https://user-images.githubusercontent.com/20341158/192356134-d5660523-ebda-4b6c-b31a-07f4d6b6f551.png)

**Comment by stephpenn1** [comment]
Checklist for SP putting into folders
#### WATER
- [ ] Basic Water Quality (conductivity, pH, ORP, Alkalinity)
- [ ] Total Suspended Solids
- [ ] Major Anions (fluoride, chlorine, nitrate, nitrite, sulfate, bromide, phosphate) *Revisit Feasibility Oct 5* 
- [ ] Major Cations (lithium, sodium, ammonium, potassium, magnesium, calcium) *Revisit Feasibility Oct 5* 
- [ ] Dissolved organic carbon
- [ ] Total dissolved nitrogen

#### SEDIMENT
- [ ] Oxygen concentration time-series 
- [ ] Bulk density
- [ ] Gravimetric water content
- [ ] Loss on ignition

#### SOIL
- [ ] pH, conductivity
- [ ] Total carbon and nitrogen
- [ ] Oxygen concentration time-series 
- [ ] Bulk density
- [ ] Gravimetric water content
- [ ] Loss on ignition

**Comment by amyerspigg** [comment]
ESS DIVE Submission checklist
https://ess-dive.lbl.gov/archive/

- [ ] Clean and organize datasets (see original issue post and steps for this)
- [ ] Compile submission metadata
- [ ] Dataset metadata (required to publish on ESS-DIVE) reporting format https://github.com/ess-dive-community/reporting-format-template-repo 
         - [ ] Dataset Title
         - [ ] DOIs 
         - [ ] Abstract
         - [ ] Keywords
         - [ ] Data Variables
         - [ ] Publication Date
         - [ ] Data Usage Rights
         - [ ] Project Affiliation 
         - [ ] Funding Organizations 
         - [ ] DOE contracts
         - [ ] Related References 
         - [ ] Dataset Contact
         - [ ] Dataset Creators 
         - [ ] Dataset Contributors 
         - [ ] Dates (start and end date)
         - [ ] Location Description
         - [ ] Bounding Box Coordinates 
         - [ ] Methods ("You may provide a citation for any related methods used that have been previously published, but we strongly recommend still including methods text in your dataset metadata that fully describe data collection and processing steps"
         - [ ]

**Comment by amyerspigg** [comment]
@kaizadp / @peterregier  who was doing the LOI check? I see several kits with no data for LOI that I THINK we should have samples for (based on the filtering of collected/not collected script PR wrote). All sediment: 
K001
K007
K029
K051
K052
K056
K058

**Comment by amyerspigg** [comment]
Metadata @stephpenn1 
K046 transition
K014 wetland

**Comment by peterregier** [comment]
I don't think LOI is me.

**Comment by amyerspigg** [comment]
Ok cool. I can't find the check list assignments since we didnt do them in github
