### ISSUE TITLE
NPOC script review

### ISSUE THREAD

**Issue by peterregier** [COMPASS-DOE/EXCHANGE#4]
@kaizadp or @stephpenn1 : can you review the NPOC script? It is theoretically done. I am trying to replace drive_find() with a flexible drive_get() call that specifies directory, but that still doesn't get around downloading data to local. Work in progress to efficiently pull data directly from GDrive....

**Comment by peterregier** [comment]
This script has been updated, and does a better job of pulling files from GDrive.

**Comment by peterregier** [comment]
Yup! I got guidance from someone not to close issues but comment closed, I defer to your git judgment

**Comment by stephpenn1** [comment]
Ah since this is small + resolved i assume its ok to close
