### ISSUE TITLE
Check K046 and K030 coordinates

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#42]

**Comment by jmcelhinny** [comment]
![image](https://user-images.githubusercontent.com/84864867/222268988-bb04a845-768b-42b2-8fd8-f953bc2b97e2.png)
it appears K030 sediment puts us in western China because of the missing - sign!
if we add the negative sign back in, the sediment location matches where the water sample was collected

**Comment by jmcelhinny** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/84864867/222269913-3a50ec0b-9f40-40da-981b-13c6dac30c1f.png">
K046 upland is in the atlantic ocean.
thinking 29.0887 needs to be 39.0887

**Comment by stephpenn1** [comment]
Updated in submission folder
