### ISSUE TITLE
Need to upload LOD file from MCRL instrument 

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#46]
https://github.com/COMPASS-DOE/EXCHANGE/blob/6b8ba5a0aa8492935744dc7a2ef4ad6c87333b16/Processing_Scripts/water_npoc_tdn.R#L28

- [x] Put file into google drive folder directory = "https://drive.google.com/drive/folders/1Mkg5UCEzt9ifKCGyr-Kn9a3LL8XuGzBa 
- [x] undo the hard coding 
- [x] update LOD to contain krusty's numbers for certain time periods @opalotenburg

**Comment by jmcelhinny** [comment]
LOD file has been updated to reflect the period when NPOC samples were run on one TOC and TDN samples on another TOC
