### ISSUE TITLE
Check the blanks 

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#48]
https://github.com/COMPASS-DOE/EXCHANGE/blob/6b8ba5a0aa8492935744dc7a2ef4ad6c87333b16/Processing_Scripts/water_npoc_tdn.R#L73

**Comment by jmcelhinny** [comment]
all blanks are 0.3 or less with standard deviations suggesting very small to fluctuations - no concern about blank correcting to negative values
