### ISSUE TITLE
All kits, All flags!!

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#51]
After #38 Checking for Kits that were not sampled, or exist but were not analyzed 

Create a final flagged kit list for the data package

**Comment by amyerspigg** [comment]
Example take the L0B flags, and create a new dataframe of the kits with the flags and what the flags mean

**Comment by amyerspigg** [comment]
Columns: Campaign, Kit ID, Transect Location, Analyte, Reason its not reported (e.g., below detection limit, not sampled, sample lost in mail)

**Comment by stephpenn1** [comment]
- Read in all L1 data (https://drive.google.com/drive/u/1/folders/1yhukHvW4kCp6mN2jvcqmtq3XA5niKVR3)
- put into wide format
- NA for sample that has data
- flag description for any sample that does not

**Comment by amyerspigg** [comment]
I believe this is resolved in the sample catalog.
