### ISSUE TITLE
FTICRMS Column names

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#53]
This is not really in L2 in the L2 folder, because it still has the duplicate naming, though the dups were removed (ie, K00Xb). This needs to be resolved. 

Also, blank column is still provided (though values appear NA).

**Comment by amyerspigg** [comment]
![Image](https://user-images.githubusercontent.com/56139567/221914745-c0e12820-854b-4c5e-b1bc-2f745bf13781.png)

**Comment by kaizadp** [comment]
@amyerspigg - do we want to just drop the "b" from the column names?

**Comment by amyerspigg** [comment]
@kaizadp Yep, thats right. Please let me know when you're done with that step :)

**Comment by kaizadp** [comment]
done. 114a1130a2eec3e7976a64256bc32defda0b0ee9
