### ISSUE TITLE
DOI by March 20

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#54]

**Comment by stephpenn1** [comment]
doi:10.15485/1960313

> This DOI will not function until the data package has been published on ESS-DIVE. The package is currently on Hold. When you’re ready for publication and would like our team to review, reply to this email chain or send an email to [ess-dive-support@lbl.gov](mailto:ess-dive-support@lbl.gov) and we’ll start the review process.
