### ISSUE TITLE
Soil conductivity

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#59]
~need to check if in SI units. SI units are decisiemens per m or microsiemens per cm~
_units checked 3/6/2023, cond is in uS/cm_

Rhodes 1996

**Comment by stephpenn1** [comment]
@kaizadp here is a [dataframe of missing ph/conductivity values](https://docs.google.com/spreadsheets/d/1jyaU8RWxtrsIub04WwA8hoUpO_1wl-GuXd1UU8rPz9I/edit?usp=sharing) that we have weights for and metadata says were collected

**Comment by stephpenn1** [comment]
only remaining checks for this analyte are the missing values above ^ and #60

**Comment by kaizadp** [comment]
Done. pH data here: https://docs.google.com/spreadsheets/d/1hNnMjyM8zelUqI-AwLeG_lrGGgLyTfztaLp1btzqxZ0/edit#gid=0

**Comment by amyerspigg** [comment]
@amyerspigg

**Comment by stephpenn1** [comment]
```
Model: Ultrameter II

Conductivity Measurement: 0-9,999 µS/cm, 10-200 mS/cm
```

make flag bounds based on what unit the instrument measured in
