### ISSUE TITLE
TSS

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#63]
- rerun code, cross check with paper
- check for missing metadata or data

**Comment by amyerspigg** [comment]
Waiting on final water quality dataset

**Comment by stephpenn1** [comment]
@amyerspigg what columns do we want in the L2 dataset? current columns are:

`"campaign"            "kit_id"              "transect_location"   "tss_mg_perl"         "total_filter_mass_g" "volume_filtered_ml"  "filters_used"        "tss_flag" `

**Comment by amyerspigg** [comment]
@stephpenn1  just saw this....I think we just want the first 4 columns
