### ISSUE TITLE
CDOM

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#64]
- rerun code, cross check with paper
- check file names
- check for missing metadata or data

**Comment by amyerspigg** [comment]
![Image](https://user-images.githubusercontent.com/56139567/231231828-920e6e0e-c02d-44a7-b2cd-8be9cd94c1e5.png)

**Comment by amyerspigg** [comment]
- [ ] @stephpenn1  check here when metadata is fixed

**Comment by amyerspigg** [comment]
Sample list uploaded `ec1_water_eems_sample_list.csv` and sample status updated in metadata sheet
