### ISSUE TITLE
oxygen drawdown rates

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#65]
-re run code, cross check with paper
- check for missing metadata or data

**Comment by amyerspigg** [comment]
- make sure not including GHG data, if so, check units

**Comment by amyerspigg** [comment]
Update: not including in EC1 datapackage. will include in EC1 paper on these data

**Comment by stephpenn1** [comment]
Sep 13: need to talk to PR about an update on these, will be included in PR's paper but not in EC1 essdive submission
