### ISSUE TITLE
Soil/Sediment Visual Metrics

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#66]

**Comment by amyerspigg** [comment]
Update: will include in future versions of the data package. Will need help standardizing this

**Comment by stephpenn1** [comment]
### Update `2023-12-20`
All columns have been standardized except `cohesion_post_lyopholization` and `notes`:

- `cohesion_post_lyopholization`: based on the entries, it seems like this could be broken into two columns (aggregated and easy to break apart), but I'd like to talk to @amyerspigg or @kaizadp about what this column means before I do so

- `notes`: good amount of repeats in here from what the other columns address, but since this is a qualitative analyte, the notes seem important here. I'd also like to go through these with AMP or KP and decide whether to remove or clean up.

**Comment by stephpenn1** [comment]
### Kits that need attention:
- [ ] K010 sediment: no data but metadata says it was collected 
- [ ] K001 and K007 need to be removed
- [ ] K046 transition and wetland switched (we know how to handle this, #60)

**Comment by kaizadp** [comment]
> * `cohesion_post_lyopholization`: based on the entries, it seems like this could be broken into two columns (aggregated and easy to break apart), but I'd like to talk to @amyerspigg or @kaizadp about what this column means before I do so
> *

I don't know the value of this column. I say drop, unless @amyerspigg thinks otherwise. Need to fix the spelling - "**lyophilization**"

**Comment by stephpenn1** [comment]
Example entries:
<img width="419" alt="Screenshot 2023-12-21 at 8 43 36 PM" src="https://github.com/COMPASS-DOE/EXCHANGE/assets/20341158/e39273ff-f06d-4a08-be5c-00d0a048478f">

**Comment by stephpenn1** [comment]
@amyerspigg and @kaizadp agree to drop `cohesion_post_lyopholization` and `notes`
