### ISSUE TITLE
make sure all transect_location value are LOWERCASE

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#67]
can use `to_lower(transect_location)`

**Comment by amyerspigg** [comment]
Dear Stephanie,

what package is to_lower in?

**Comment by amyerspigg** [comment]
fyi I just used 
tolower()

**Comment by stephpenn1** [comment]
Dear Allison,

to_lower doesnt exist, apparently i made it up. please use tolower

regards,
Stephanie
