### ISSUE TITLE
check FTICRMS for missing kits

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#72]

**Comment by amyerspigg** [comment]
![Image](https://user-images.githubusercontent.com/56139567/231258177-3abe39b5-5bfa-4b73-b80b-23a140e38a96.png)

**Comment by amyerspigg** [comment]
- [ ] @stephpenn1  we need to check K027 & K044 together for notes

**Comment by amyerspigg** [comment]
K027 1L not used (compromised) 
K044 everything looks like it should exist. It was SPE'd AND eluted.

**Comment by stephpenn1** [comment]
`K044` was not sent to emsl, needs to have a flag `sample not sent for analysis`

**Comment by amyerspigg** [comment]
Completed sample list, and uploaded to drive: https://drive.google.com/drive/folders/1a55sRVu-XaK-TUCkL_zyqRH7zaV5OSIv
