### ISSUE TITLE
check over flmd for sample catalog

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#81]
View [here](https://drive.google.com/file/d/18bWD2UWzD6JMBlv8id2-JI-io2UVL5xO/view?usp=sharing), is the sample catalog description good enough?

**Comment by amyerspigg** [comment]
Suggested edits:

`Sample catalog for a given analyte, flags provided for any non-available sample data. If data is provided and text reads anything other than "data available", this constitutes warnings provided for any samples diverging from normal protocols (e.g. less than 3 replicate values used for total carbon). Values "not applicable" mean that the data type is not applicable for the sample type`

**Comment by stephpenn1** [comment]
Perfect, i only changed the last sentence to what you wrote in the readme
