### ISSUE TITLE
How do we want the catalog organized?

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/EXCHANGE#82]
https://github.com/COMPASS-DOE/EXCHANGE/blob/59bc65a6d77434f5e0080fcf0b6004706a08f397/Processing_Scripts/sample_catalog_matrix.R#L81

**Comment by amyerspigg** [comment]
Right now it goes, soils, sediments, water by kit. I propose we do it by kit first

**Comment by stephpenn1** [comment]
good catch

**Comment by stephpenn1** [comment]
arranged by `kit_id` and `transect_location` now
