### ISSUE TITLE
Base Cations

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/EXCHANGE#89]

**Comment by kaizadp** [comment]
@stephpenn1 - processing done, ready for final QC and conversion to L2
@amyerspigg

**Comment by stephpenn1** [comment]
Samples to check on:
- [ ] K046 transition and wetland switchs as per #60 
- [ ] K010 sediment - no data but says collected
- [ ] K024 wetland - no data but says collected
- [ ] K050 upland - no data but says collected
- [ ] K001 and K007 need to be removed as per #70 
- [ ] K018 and K027 have compromised samples that need removing

**Comment by kaizadp** [comment]
@stephpenn1 I will check our sample (weighing) sheets for the missing samples. It’s possible we didn’t have enough material for them.

**Comment by stephpenn1** [comment]
@kaizadp thanks, we already know about `K010 sediment` so just check `K024 wetland` and `K050 upland`

**Comment by stephpenn1** [comment]
Thanks! @kaizadp to clarify for `K024 wetland` are you saying the entire jar was compromised? or just the sample you had for this analyte? I'm going to update the sample list if it's the entire jar

**Comment by kaizadp** [comment]
correct - "sample compromised" only for this analysis. the rest of the kit was fine.
